### ISSUE TITLE
Need token for a node's parent Group

### ISSUE THREAD

**Issue by ericras** [unlcms/UNL-CMS-2#39]
See https://www.drupal.org/node/2774827

**Comment by ericras** [comment]
Patch has been added to this repo

https://www.drupal.org/node/2774827#comment-11907035

**Comment by mfairchild365** [comment]
I'm closing this https://github.com/unlcms/UNL-CMS-2/commit/566f2f4ad85bd22b1c0c23f3a58642e662243b25
