### ISSUE TITLE
IMCE folder provisioning by group

### ISSUE THREAD

**Issue by ericras** [unlcms/UNL-CMS-2#9]
In Drupal 7, the following could be pasted after "<root>/" in the IMCE settings UI:

```
php: 
        $names = array();
        foreach(views_get_view_result('og_groups_by_user') as $group){
          array_push($names,'statewide/'.$group->field_field_url_path[0]['rendered']['#markup']);
        }
        return $names;
```

In doesn't look like the D8 version of IMCE supports putting php in the text box.  It supports tokens but there's not a [current-user:groups] token.  Tokens are kind of meant for a single value, not an array.  This probably needs to be accomplished in code.

**Comment by ericras** [comment]
<img width="988" alt="screen shot 2016-12-23 at 10 36 43 am" src="https://cloud.githubusercontent.com/assets/446357/21458396/b7a0218e-c8fb-11e6-9b7d-812595cd0288.png">

**Comment by ericras** [comment]
```
$grp_membership_service = \Drupal::service('group.membership_loader');
$grps = $grp_membership_service->loadByUser($user);
foreach ($grps as $grp) {
        $groups[] = $grp->getGroup();
}
```

**Comment by kabel** [comment]
Their aren't any hooks for this in the 8.x version (as you alluded to), so we'll likely have to add a patch to support this kind of folder permission injection at http://cgit.drupalcode.org/imce/tree/src/Imce.php?h=8.x-1.x#n107

**Comment by mfairchild365** [comment]
There may not be hooks, but there are plugins!

**Comment by mfairchild365** [comment]
I made a PR that implements a plugin that will accomplish this: https://github.com/unlcms/imce_groups/pull/1
